name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile
        run: g++ -o main main.cpp

      - name: Execute
        run: ./main

      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: main

